### ISSUE TITLE
Issue in getRowCount example

### ISSUE THREAD

**Issue by chasingtheflow** [kr4uzi/ServiceNow-Guide#1]
Hey,

Great resource --- thanks for putting it together. 

Subtle thing I noticed in your GlideAggregate example is that you return the aggregate as-is and don't cast it to a number. Which is unexpected, especially as the other branch of your unary operator returns a number (`0`). 

```javascript
function numberOfEmailIncidentsBad() {
  var gr = new GlideRecord("incident");
  gr.addActiveQuery();
  gr.addQuery("description", "CONTAINS", "email");
  gr.query();
  return gr.getRowCount();
}

function numberOfEmailIncidentsGood() {
  var ga = new GlideAggregate("incident");
  ga.addActiveQuery();
  ga.addQuery("description", "CONTAINS", "email");
  ga.addAggregate("COUNT");
  ga.query();
  return ga.next() ? ga.getAggregate("COUNT") : 0;  // <-- your return value may be a string or a number
}
```

When I use GlideAggregate in this scenario I typically just cast it with `+ga.getAggregate("COUNT")` though you may prefer a more explicit method. You even address this topic of varying return type later in the article so I suspect you've just overlooked this.

**Comment by kr4uzi** [comment]
You're absolutely right. thanks for the update, i've updated the function definition (+ is also my preferred casting method).
